spring:
  application:
    name: user-service
  cloud:
    openfeign:
      client:
        config:
          user-service:
            connectTimeout: 1000
            readTimeout: 1000
    config:
      enabled: false  # TODO
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres:5432/colabadb}
    username: ${SPRING_DATASOURCE_USERNAME:colaba_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/colabadb}
    user: ${SPRING_DATASOURCE_USERNAME:colaba_user}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: 8081

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 2000
        logger-level: basic
        error-decoder: com.example.colaba.shared.feign.FeignErrorDecoder
  circuitbreaker:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    packages-to-scan: com.example.colaba.user.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

resilience4j:
  circuitbreaker:
    instances:
      userClient:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      projectClient:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowSize: 10

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakerevents,circuitbreakers

logging:
  level:
    io.github.resilience4j: DEBUG
    com.example.colaba: INFO