spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  cloud:
    config:
      enabled: false  # TODO
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres:5432/colabadb}
    username: ${SPRING_DATASOURCE_USERNAME:colaba_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/colabadb}
    user: ${SPRING_DATASOURCE_USERNAME:colaba_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mvc:
    favicon:
      enabled: false

server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        errorDecoder: com.example.colaba.shared.feign.FeignErrorDecoder

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs-user
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    config-url: /v3/api-docs-user/swagger-config
    url: /v3/api-docs-user
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - url: /v3/api-docs-user
        name: User Service API
  packages-to-scan: com.example.colaba.user.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json