spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: task-service
  cloud:
    config:
      enabled: false  # TODO
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/colabadb}
    username: ${SPRING_DATASOURCE_USERNAME:colaba_user}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  mvc:
    favicon:
      enabled: false

server:
  port: 8083

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
        error-decoder: com.example.colaba.shared.feign.FeignErrorDecoder

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs-task
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    config-url: /v3/api-docs-task/swagger-config
    url: /v3/api-docs-task
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    urls:
      - url: /v3/api-docs-task
        name: Task Service API
  packages-to-scan: com.example.colaba.task.controller
  default-consumes-media-type: application/json
  default-produces-media-type: application/json